const CHANGE_INTERVAL = 'CHANGE_INTERVAL';
const CHANGE_TIMER_STATE = 'CHANGE_TIMER_STATE';
const CHANGE_TIMER_TIME = 'CHANGE_TIMER_TIME';
const RESET_INTERVAL = 'RESET_INTERVAL';

export {
    CHANGE_INTERVAL,
    CHANGE_TIMER_STATE,
    CHANGE_TIMER_TIME,
    RESET_INTERVAL,
};
